config/routes.rb
Neday::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to => "home#index"
  resources :users do
    scope :module => :user do
      resources :events
      resources :visited_events , :only => [:index]
    end
  end
  namespace :user, :as => :my do
    resources :events
  end
  resources :events
  resources :places
  resources :event_members, :only => [:create, :destroy]

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :owner, :class_name => 'User'
  belongs_to :place
  belongs_to :sport
  attr_accessible :start_at, :sport_id, :place_id, :place_attributes, :note

  validates :owner_id, :start_at, :sport_id, :presence => true
  accepts_nested_attributes_for :place

  has_many :event_members
  has_many :members, :through => :event_members
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic :size => 50
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :facebook_id, :avatar,
                  :remote_avatar_url, :remove_avatar, :avatar_cache, :vkontakte_id, :location_attributes, :twitter_id, :google_id,
                  :contacts_attributes, :user_sports_attributes, :location, :sport_ids
  has_one :location, :as => :locationable
  accepts_nested_attributes_for :location

  delegate :country, :city, :address, :to => :location, :allow_nil => true
  has_many :contacts, :class_name => 'UserContact', :dependent => :destroy
  accepts_nested_attributes_for :contacts
  has_many :user_sports, :dependent => :destroy
  accepts_nested_attributes_for :user_sports
  has_many :sports, :through => :user_sports
  has_many :events, :foreign_key => 'owner_id'
  has_many :event_members
  has_many :visited_events, :through => :event_members, :source =>:event

  def name
    "#{first_name} #{last_name}".strip
  end

  def self.sign_in_or_build_new_user(auth_data, signed_in_resource, kind)
    return signed_in_resource if signed_in_resource
    data = auth_data.info
    User.find_by_email(data.email) || User.send("find_by_#{kind}_id", auth_data.uid) ||
      User.new(:email             => data.email,
               :password          => Devise.friendly_token[0,20],
               :first_name        => data.first_name,
               :last_name         => data.last_name,
               "#{kind}_id"       => auth_data.uid,
               :remote_avatar_url => data.image, :location_attributes => {:address => data.location})
  end

  def uses_gravatar?
    !avatar.present?
  end

  def existed_avatar
    uses_gravatar? ? gravatar_url : avatar
  end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  load_and_authorize_resource

  def index
    @events = Event.paginate(:page => params[:page])
  end

end

app/controllers/user/events_controller.rb
class User::EventsController < InheritedResources::Base

  private
  
  def begin_of_association_chain
    User.find_by_id(params[:user_id]) || current_user
  end

end

app/controllers/user/visited_events_controller.rb
class User::VisitedEventsController < InheritedResources::Base
 
  belongs_to :user, :finder => :find_by_id!, :param => :user_id

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  %w(facebook vkontakte twitter google).each do |net|
    define_method(net) do
      @user = User.sign_in_or_build_new_user(request.env["omniauth.auth"], current_user, net)
      auth_user_action(net)
    end
  end

  private
  def auth_user_action(kind)
    kind = kind.to_s.titleize
    if @user.new_record?
      if @user.save
        flash[:notice] = t("devise.omniauth_callbacks.success", :kind => kind)
        sign_in_and_redirect @user, :event => :authentication
      else
        flash[:error] = t("devise.omniauth_callbacks.failure", :kind => kind)
        render :template => 'devise/registrations/new'
      end
    else
      flash[:notice] = t("devise.omniauth_callbacks.success", :kind => kind)
      sign_in_and_redirect @user, :event => :authentication
    end
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  load_and_authorize_resource

  def index
    @users = User.paginate(:page => params[:page])
  end

end

app/helpers/event_helper.rb
module EventHelper
  def time_before_event(event)
    Time.diff(event.start_at, Time.now)[:day]
  end

end

app/views/user/events/_event.html.erb
<li class=''>
  <div class="row">
    <div class="span1">
      <%= image_tag(event.sport.icon, :alt => event.sport.name, :title => event.sport.name) %>
    </div>
    <div class="span3">
      <p><%= event.place.name %></p>
      <p><%= event.start_at %></p>
    </div>
    <div class="span3">
      <%= link_to "Детально", event %>
      <%= link_to "Редактировать", edit_user_event_path(current_user, event) %>
    </div>
    <%= render :partial => 'add_remove_eventmember_button', :locals => {:event => event} %>
  </div>
</li>

app/views/user/events/_form.html.erb
<%= simple_form_for [:user, @event], :html => { :class => "form-horizontal" } do |f| %>
  <div class="well">
    <div class="page-header"><h1>Создание нового события</h1></div>
    <%= f.association :sport, :prompt => 'Выберите' %>
    <%= f.simple_fields_for :place, :build_association => true do |fp| %>
      <%= fp.input :name, :placeholder => 'Название места' %>
      <%= fp.simple_fields_for :location, :build_association => true do |fl| %>
        <%= fl.input :address, :placeholder => 'Место проведения' %>
      <% end %>
    <% end %>
    <%= f.input :start_at, :input_html => {:class => 'datepicker'}, :as => :string, :placeholder => 'Дата' %>
    <div class="form-actions">
      <%= link_to 'Создать', 'submit', :class => 'btn btn-primary' %>
      <%= link_to 'Отмена', user_path(current_user), :class => 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/user/events/index.html.erb
<div class='well'>
  <div class="page-header"><h1>Список событий</h1></div>
  <ul class="unstyled">
    <%= render @events %>
  </ul>
</div>

app/views/user/events/new.html.erb
<%= render 'form' %>