config/routes.rb
Neday::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to => "home#index"
  resources :users do
    scope :module => :user do
      resources :events
      resources :visited_events , :only => [:index]
    end
  end
  namespace :user, :as => :my do
    resources :events
  end
  resources :events
  resources :places
  resources :event_members, :only => [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic :size => 50
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :facebook_id, :avatar,
                  :remote_avatar_url, :remove_avatar, :avatar_cache, :vkontakte_id, :location_attributes, :twitter_id, :google_id,
                  :contacts_attributes, :user_sports_attributes, :location, :sport_ids
  has_one :location, :as => :locationable
  accepts_nested_attributes_for :location

  delegate :country, :city, :address, :to => :location, :allow_nil => true
  has_many :contacts, :class_name => 'UserContact', :dependent => :destroy
  accepts_nested_attributes_for :contacts
  has_many :user_sports, :dependent => :destroy
  accepts_nested_attributes_for :user_sports
  has_many :sports, :through => :user_sports
  has_many :events, :foreign_key => 'owner_id'
  has_many :event_members
  has_many :visited_events, :through => :event_members, :source =>:event

  def name
    "#{first_name} #{last_name}".strip
  end

  def self.sign_in_or_build_new_user(auth_data, signed_in_resource, kind)
    return signed_in_resource if signed_in_resource
    data = auth_data.info
    User.find_by_email(data.email) || User.send("find_by_#{kind}_id", auth_data.uid) ||
      User.new(:email             => data.email,
               :password          => Devise.friendly_token[0,20],
               :first_name        => data.first_name,
               :last_name         => data.last_name,
               "#{kind}_id"       => auth_data.uid,
               :remote_avatar_url => data.image, :location_attributes => {:address => data.location})
  end

  def uses_gravatar?
    !avatar.present?
  end

  def existed_avatar
    uses_gravatar? ? gravatar_url : avatar
  end
end

app/controllers/user/events_controller.rb
class User::EventsController < InheritedResources::Base

  private
  
  def begin_of_association_chain
    User.find_by_id(params[:user_id]) || current_user
  end

end

app/controllers/user/visited_events_controller.rb
class User::VisitedEventsController < InheritedResources::Base
 
  belongs_to :user, :finder => :find_by_id!, :param => :user_id

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  %w(facebook vkontakte twitter google).each do |net|
    define_method(net) do
      @user = User.sign_in_or_build_new_user(request.env["omniauth.auth"], current_user, net)
      auth_user_action(net)
    end
  end

  private
  def auth_user_action(kind)
    kind = kind.to_s.titleize
    if @user.new_record?
      if @user.save
        flash[:notice] = t("devise.omniauth_callbacks.success", :kind => kind)
        sign_in_and_redirect @user, :event => :authentication
      else
        flash[:error] = t("devise.omniauth_callbacks.failure", :kind => kind)
        render :template => 'devise/registrations/new'
      end
    else
      flash[:notice] = t("devise.omniauth_callbacks.success", :kind => kind)
      sign_in_and_redirect @user, :event => :authentication
    end
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  load_and_authorize_resource

  def index
    @users = User.paginate(:page => params[:page])
  end

end

app/views/users/_avatar.html.erb
<div class="tab-pane" id="avatar-tab">
  <header><h4>Текущий аватар</h4></header>
  <%= image_tag @user.existed_avatar, :alt => @user.name, :title => @user.name %>
  <%= f.input :avatar_cache, :as => :hidden %>
  <%= f.label :remove_avatar do %>
    <% if @user.uses_gravatar? %>
      <%= link_to 'Gravatar', 'http://gravatar.com/emails', :target => :blank %>
    <% else %>
      <%= f.check_box :remove_avatar %>
      Удалить аватар
    <% end %>
  <% end %>
  <%= f.file_field :avatar %>
  <div class="control-group">
    <div class="controls">
      <div class="input-prepend">
        <span class="add-on">
          <div class="icon-picture"></div>
        </span>
        <%= f.text_field :remote_avatar_url, :placeholder => 'http://myavatar.com/avatar.png' %>
      </div>
    </div>
  </div>
</div>

app/views/users/_contacts.html.erb
<div class="tab-pane" id="contacts-tab">
  <header><h4>Контакты</h4></header>
  <%= f.input :email, :hint => 'Не рекомендуется изменять', :label => false do %>
    <div class="input-prepend">
      <span class="add-on"><div class='icon-envelope'></div></span>
      <%= f.email_field :email, :placeholder => 'Электронная почта' %>
    </div>
  <% end %>
  <%= f.fields_for :contacts do |fc| %>
    <%= fc.collection_select :contact_type_id, ContactType.all, :id, :name, {:include_blank => 'Тип контакта'} %>
    <%= fc.link_to_remove "Удалить" %>
    <%= fc.input :value, :label => false do %>
      <div class="input-prepend">
        <span class="add-on">
          <div class="icon-th-list"></div>
        </span>
        <%= fc.text_field :value, :placeholder => 'Контакт' %>
      </div>
    <% end %>
  <% end %>
  <%= f.link_to_add "Добавить", :contacts %>
</div>

app/views/users/_location.html.erb
<div class="tab-pane active" id="location-tab" >
  <header><h4>Место обитания</h4></header>
  <%= f.simple_fields_for :location, :build_association => true do |fl| %>
    <%= fl.input :address, :label => false do %>
      <%= input_prepend('icon-map-marker') do %>
        <%= fl.text_field :address, :placeholder => 'Адрес', :class => 'input-xxlarge' %>
      <% end %>
    <% end %>
    <div class="yandex-map">
      <%= add_location_to_map(@user.location) %>
    </div>
  <% end %>
</div>

app/views/users/_sport.html.erb
<div class="tab-pane" id="sport-tab">
  <header><h4>Интересующие виды спорта</h4></header>
  <%= f.fields_for :user_sports do |fs| %>
    <%= fs.collection_select :sport_id, Sport.all, :id, :name, {:include_blank => 'Вид спорта'} %>
    <%= fs.link_to_remove "Удалить" %>
  <% end %>
  <%= f.link_to_add "Добавить", :user_sports %>
</div>

app/views/users/created_events.html.erb
<%= render 'events_list' %>

app/views/users/edit.html.erb
<%= simple_nested_form_for @user, :html => { :class => "form-vertical" } do |f| %>
  <div class="well">
    <header>
      <%= f.text_field :first_name, :placeholder => 'Имя' %>
      <%= f.text_field :last_name, :placeholder => 'Фамилия' %>
    </header>
    <div class="tabbable">
      <ul class="nav nav-tabs">
        <li class="active"><%= link_to 'Адрес', '#location-tab', :data => {:toggle => 'tab'}, :class => 'active' %></li>
        <li><%= link_to 'Аватар', '#avatar-tab', :data => {:toggle => 'tab'} %></li>
        <li><%= link_to 'Контакты', '#contacts-tab', :data => {:toggle => 'tab'} %></li>
        <li><%= link_to 'Виды спорта', '#sport-tab', :data => {:toggle => 'tab'} %></li>
       </ul>
      <div class="tab-content">
        <%= render :partial => 'contacts', :locals => {:f => f} %>
        <%= render :partial => 'location', :locals => {:f => f} %>
        <%= render :partial => 'sport', :locals => {:f => f} %>
        <%= render :partial => 'avatar', :locals => {:f => f} %>
      </div>
      <div class="form-actions">
        <%= link_to 'Сохранить изменения', 'submit', :class => 'btn btn-primary' %>
        <%= link_to 'Отмена', user_path(@user), :class => 'btn btn-danger' %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class='well'>
  <div class="page-header"><h1>Список оппонентов</h1></div>
  <ul class="unstyled">
    <% @users.each do |user| %>
      <li class=''>
        <div class="row">
          <div class="span1">
              <%= link_to user do %>
                <%= image_tag user.existed_avatar, :alt => user.name, :title => user.name %>
              <% end %>
          </div>
          <div class="span3">
            <ul class='unstyled'>
              <li><%= link_to user.name, user %></li>
              <li><%= mail_to user.email %></li>
              <li><%= link_to 'События пользователя', user_events_path(user) %></li>
              <li><%= link_to "#{user.name} участвует в событиях", user_visited_events_path(user) %></li>
              <% user.contacts.each do |c| %>
                <li><%= c.name %></li>
              <% end %>
            </ul>
          </div>
          <div class="span2">
            <ul class='unstyled'>
              <% user.sports.each do |sport| %>
                <li><%= sport.name %></li>
              <% end %>
            </ul>
          </div>
          <div class="span2">
            <%= user.address %>
          </div>
        </div>
        <hr />
      </li>
    <% end %>
  </ul>
  <%= will_paginate %>
</div>

app/views/users/show.html.erb
<div class="well">
  <header class="page-header">
    <div class="row">
      <div class="span1">
        <%= image_tag @user.existed_avatar, :alt => @user.name, :title => @user.name  %>
      </div>
      <div class="span6">
        <h2><%= @user.name  %></h2>
      </div>
      <div class="span1">
        <% if can? :edit, (@user) %>
          <%= link_to 'Редактировать', edit_user_path(@user)%>
        <% end %>
      </div>
    </div>
    <section class="row">
      <div class="span4">
        <strong>Контакты</strong>
        <dl class="page-header">
          <dt>Email</dt>
          <dd><%= @user.email %></dd>
            <% @user.contacts.each do |c| %>
              <dt><%= c.contact_type.name %></dt>
              <dd><%= c.value %></dd>
            <% end %>
        </dl>
        <strong>Интересующие виды спорта</strong>
        <ul>
          <% @user.sports.each do |s| %>
            <li><%= s.name %></li>
          <% end %>
        </ul>
        <ul class ="unstyled">
        <li><strong><%= link_to 'События пользователя', user_events_path(@user)%></strong></li>
        <li><strong><%= link_to "#{@user.name} участвует в событиях", user_visited_events_path(@user) %></strong></li>
        <ul>
      </div>
      <div class="span4">
        <strong>Место обитания</strong>
        <address><%= @user.address %></address>
        <div class="yandex-map">
          <%= add_location_to_map(@user.location) %>
          <%= add_location_to_map(current_user.try(:location)) %>
        </div>
      </div>
    </section>
  </header>
</div>