config/routes.rb
Neday::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to => "home#index"
  resources :users do
    scope :module => :user do
      resources :events
      resources :visited_events , :only => [:index]
    end
  end
  namespace :user, :as => :my do
    resources :events
  end
  resources :events
  resources :places
  resources :event_members, :only => [:create, :destroy]

end

app/views/shared/_events_list.html.erb
<div class='well'>
  <div class="page-header"><h1>Список событий</h1></div>
  <ul class="unstyled">
    <% @events.each do |event| %>
      <li class=''>
        <div class="row">
          <div class="span1">
            <%= image_tag(event.sport.icon, :alt => event.sport.name, :title => event.sport.name) %>
          </div>
          <div class="span3">
            <p><%= event.place.name %></p>
            <p><%= event.start_at %></p>
          </div>
          <div class="span3">
            <p>Вакантных мест: <%= event.max_number_members - event.members.count %></p>
            <%= link_to "Детально", event %>
          </div>
          <%= render :partial => '/shared/add_remove_eventmember_button', :locals => {:event => event} %>
        </div>
      </li>
    <% end %>
  </ul>
  <%#= will_paginate %>
</div>

app/views/shared/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target='.nav-collapse' data-toggle='collapse'>
        <span class="i-bar"></span>
        <span class="i-bar"></span>
        <span class="i-bar"></span>
      </a>
      <%= link_to 'Neday', root_path, :class => 'brand' %>
      <div class="nav-collapse">
        <%= render_navigation :context => :main %>
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            <%= "Привет, #{link_to current_user.first_name, current_user}".html_safe %>
          <% else %>
            <%= link_to 'Войти', new_session_path(:user) %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_like_buttons.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1&appId=<%= Settings.fb.app_id %>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script type="text/javascript">
  window.___gcfg = {lang: 'ru'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
<!-- Put this script tag to the <head> of your page -->
<script type="text/javascript" src="http://userapi.com/js/api/openapi.js?47"></script>

<script type="text/javascript">
  VK.init({apiId: <%= Settings.vk.app_id %>, onlyWidgets: true});
</script>

<!-- Put this div tag to the place, where the Like block will be -->
<script type="text/javascript">
VK.Widgets.Like("vk_like", {type: "button", height: 24});
</script>